### ISSUE TITLE
ATOM feed

### ISSUE THREAD

**Issue by MaryBethBaker** [gcdigital-gcnumerique/digital-canada-ca#2]
Quick question: Is your blog using a ATOM feed as required by the TBS standard or an RSS feed? 

Thanks!
mb

**Comment by TouficS** [comment]
the blog page seems to be missing an H1 http://digital.canada.ca/2017/07/18/launch-of-the-canadian-digital-service/

**Comment by mcman12** [comment]
Hi Mary Beth, yes it's ATOM. just fixed the url in the feed in commit  8d0ecfc
thanks for flagging!
Toufic, creating a separate issue #3 for the H1... good catch!

**Comment by MaryBethBaker** [comment]
Thanks @mcman12

Hey to @TouficS - hope things are well at IRCC :+1:
