### ISSUE TITLE
H1 missing on blog pages

### ISSUE THREAD

**Issue by mcman12** [gcdigital-gcnumerique/digital-canada-ca#3]
As mentioned in comment in issue #2 
Blog pages missing H1

**Comment by yeremia-d** [comment]
Fixed in b715be8d287511ba6e8a93084b742983c9828042

**Comment by TouficS** [comment]
@yeremia-d I think the default H1 has a white font. now the title is invisible (white on white)

**Comment by yeremia-d** [comment]
Good catch, push the fix. Thanks :)
