### ISSUE TITLE
disable header background autoplay video

### ISSUE THREAD

**Issue by scilib** [gcdigital-gcnumerique/digital-canada-ca#4]
Consider disabling the autoplay background video currently on the site.

Autoplaying background video or animation can trigger various motion-related disorders.

[Why iOS 7 is making some users sick](https://www.theguardian.com/technology/2013/sep/27/ios-7-motion-sickness-nausea)

In general I would say any autoplay video whether foreground or background is not a best practice.

Safari in the new Mac High Sierra OS (10.13) will reportedly [block autoplay video](https://techcrunch.com/2017/06/05/auto-play-block/).

For now I am blocking the background video with Adblock Plus filter: digital.canada.ca##div.page-banner--video

**Comment by TouficS** [comment]
or provide the user with the option to stop or pause it

**Comment by mcman12** [comment]
we've added a pause/play button on the website, we will also remove the video on mobile view as it has a problem on Android. commit for the changes will follow.
thanks so much @TouficS and @scilib

**Comment by scilib** [comment]
Adding a pause button is a good step forward.
